import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Navbar() {
  return (
    <nav className="w-full flex items-center justify-center py-4 border-b border-gray-200 mb-8">
      <ul className="flex gap-8 text-lg font-medium">
        <li>
          <Link href="/" className="hover:text-blue-600 transition">Home</Link>
        </li>
        <li>
          <Link href="/about" className="hover:text-blue-600 transition">About</Link>
        </li>
        <li>
          <Link href="/projects" className="hover:text-blue-600 transition">Projects</Link>
        </li>
        <li>
          <Link href="/photos" className="hover:text-blue-600 transition">Photos</Link>
        </li>
      </ul>
    </nav>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
